# This YAML file lists all *non-namespaced* objects that the operator
# needs to do its job when running inside the cluster.
#
# See also `opeator-namespaced.yaml`
---
# IngressClass/wordpress

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: wordpress
spec:
  controller: epfl.ch/ingress-wordpress

---
# ClusterRole/wp-nginx
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wp-nginx
rules:
  - apiGroups: ['']
    resources:
    - configmaps
    - endpoints
    - pods
    - secrets
    verbs: ['list', 'watch']
  - apiGroups: ['networking.k8s.io']
    resources:
    - ingressclasses
    verbs: ['get', 'list', 'watch']

---
# ClusterRole/wp-operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wp-operator
rules:
  - apiGroups: ['apiextensions.k8s.io']
    resources: ['customresourcedefinitions']
    verbs: ['list', 'watch']
