<?php

class Enlighter extends Plugin
{
	protected $pluginPath = "enlighter/Enlighter.php";
	private $enlighterOptions = array (
		'translation-enabled' => true,
		'enlighterjs-init' => 'inline',
		'enlighterjs-assets-js' => true,
		'enlighterjs-assets-themes' => true,
		'enlighterjs-assets-themes-external' => false,
		'enlighterjs-selector-block' => 'pre.EnlighterJSRAW',
		'enlighterjs-selector-inline' => 'code.EnlighterJSRAW',
		'enlighterjs-indent' => 4,
		'enlighterjs-ampersandcleanup' => true,
		'enlighterjs-linehover' => true,
		'enlighterjs-rawcodedbclick' => false,
		'enlighterjs-textoverflow' => 'break',
		'enlighterjs-linenumbers' => true,
		'enlighterjs-theme' => 'enlighter',
		'enlighterjs-retaincss' => false,
		'toolbar-visibility' => 'show',
		'toolbar-button-raw' => true,
		'toolbar-button-copy' => true,
		'toolbar-button-window' => true,
		'tinymce-backend' => false,
		'tinymce-frontend' => false,
		'tinymce-formats' => true,
		'tinymce-autowidth' => false,
		'tinymce-tabindentation' => false,
		'tinymce-keyboardshortcuts' => false,
		'tinymce-font' => 'sourcecodepro',
		'tinymce-fontsize' => '0.7em',
		'tinymce-lineheight' => '1.4em',
		'tinymce-color' => '#000000',
		'tinymce-bgcolor' => '#f9f9f9',
		'gutenberg-backend' => true,
		'quicktag-backend' => false,
		'quicktag-frontend' => false,
		'quicktag-mode' => 'html',
		'shortcode-mode' => 'disabled',
		'shortcode-inline' => true,
		'shortcode-type-generic' => false,
		'shortcode-type-language' => false,
		'shortcode-type-group' => false,
		'shortcode-filter-content' => true,
		'shortcode-filter-excerpt' => true,
		'shortcode-filter-widget' => false,
		'shortcode-filter-comment' => false,
		'shortcode-filter-commentexcerpt' => false,
		'gfm-enabled' => false,
		'gfm-inline' => true,
		'gfm-language' => 'raw',
		'gfm-filter-content' => true,
		'gfm-filter-excerpt' => true,
		'gfm-filter-widget' => false,
		'gfm-filter-comment' => false,
		'gfm-filter-commentexcerpt' => false,
		'compat-enabled' => false,
		'compat-crayon' => false,
		'compat-type1' => false,
		'compat-type2' => false,
		'compat-filter-content' => true,
		'compat-filter-excerpt' => true,
		'compat-filter-widget' => false,
		'compat-filter-comment' => false,
		'compat-filter-commentexcerpt' => false,
		'cache-custom' => false,
		'cache-path' => '',
		'cache-url' => '',
		'dynamic-resource-invocation' => true,
		'ext-infinite-scroll' => false,
		'ext-ajaxcomplete' => false,
		'bbpress-shortcode' => false,
		'bbpress-markdown' => false,
	);

	public function updateOptions()
	{
		update_option( 'enlighter-options', $this->enlighterOptions );
	}
}
