# Any and all Kubernetes objects that are necessary and sufficient
# to run the controller as a pod.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-olm-controller
  namespace: placeholder
spec:
  selector:
    matchLabels:
      wordpress-operator-role: olm-controller
  replicas: 1
  template:
    metadata:
      labels:
        wordpress-operator-role: olm-controller
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: wordpress-olm-controller
      containers:
      - name: controller
#       image: controller:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 256Mi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wordpress-olm-controller
rules:
# The controller needs permission to create and delete all
# objects in ../operator-non-namespaced.yaml:
- # ⚠ `resourceNames` doesn't work on the "create" verb;
  # see https://stackoverflow.com/a/65219397 . Bummer
  apiGroups: ["networking.k8s.io"]
  resources: ["ingressclasses"]
  verbs: ["create"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingressclasses"]
  resourceNames: ["wordpress"]
  verbs: ["*"]
# Likewise, the controller needs to create and delete all
# objects in  ../operator-namespaced.yaml:
- apiGroups:
  - apps
  resources:
  - deployments
  resourceNames:
  - wp-operator
  verbs: ["*"]
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: ["*"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  resourceNames: ["wp-operator"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["*"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  - clusterroles
  resourceNames:
  - wp-operator
  - wp-nginx
  - wp-cron
  verbs: ["*"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  - clusterroles
  verbs: ["create"]
# The controller creates namespace-specific ClusterRoleBinding's, whose names
# we cannot predict. It therefore needs the entire set of rights on that specific
# kind:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs: ["*"]
# All Kopf programs (controller and operator alike) create so-called
# “dynamic” clients, and they whine if they cannot list CRDs:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["list", "watch"]
# And on top of all that, the controller is only able
# to grant permissions (by means of creating `Role` objects)
# if it wields said permissions itself:
# (see: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#restrictions-on-role-creation-or-update).
# 💡 That means that changes you make here (e.g. additional permissions) have no effect on the operator per se!!
# You need to tell the controller to grant them to the operator by editing the
# Role object in ../operator-namespaced.yaml as well.
- apiGroups: ['wordpress.epfl.ch']
  resources:
  - wordpresssites
  - wordpresssites/status
  verbs: ['*']
- apiGroups: ['networking.k8s.io']
  resources:
  - ingresses
  verbs: ['*']
- apiGroups: ['']
  resources:
  - events
  verbs: ['create', 'patch']
- apiGroups: ['k8s.mariadb.com']
  resources:
  - backups
  - connections
  - databases
  - grants
  - mariadbs
  - restores
  - sqljobs
  - users
  verbs: ['*']
- apiGroups: ['']
  resources:
  - secrets
  verbs: ['*']
- apiGroups: ['']
  resources: ['configmaps']
  resourceNames: ['wp-operator-lock']
  verbs: ['*']
  # Again, `resourceNames` doesn't work for create:
- apiGroups: ['']
  resources: ['configmaps']
  verbs: ["create"]
- apiGroups: ['route.openshift.io']
  resources: ['routes', "routes/custom-host"]
  verbs: ["*"]
- apiGroups: ['networking.k8s.io']
  resources:
  - ingressclasses
  verbs: ['get', 'list', 'watch']
# Same as above for the permissions to be granted to
# `ServiceAccount/wp-nginx` (the one for the `Deployment/` of the same
# name). As seen in the `role/wp-nginx` object in `../operator-namespaced.yaml`:
- apiGroups: ['']
  resources:
  - namespaces
  verbs: ['get']
- apiGroups: ['networking.k8s.io']
  resources:
  - ingresses/status
  verbs: ['update']
- apiGroups: ['']
  resources:
  - pods
  - services
  verbs: ['get', 'list', 'watch']
- apiGroups: ['discovery.k8s.io']
  resources:
  - endpointslices
  verbs: ['get', 'list', 'watch']
- apiGroups: ['']
  resources:
  - configmaps
  resourceNames:
  - wp-nginx
  verbs: ['get']
# As seen in `../operator-non-namespaced.yaml`:
- apiGroups: ['']
  resources:
  - configmaps
  - endpoints
  - pods
  - secrets
  verbs: ['list', 'watch']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wordpress-olm-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wordpress-olm-controller
subjects:
- kind: ServiceAccount
  name: wordpress-olm-controller
  namespace: placeholder
