---

apiVersion: v1
kind: Service
metadata:
  name: wordpressite-conversion-webhook
  namespace: wordpress-test
spec:
    type: ClusterIP
    selector:
      app: wordpressite-conversion-webhook
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
